import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import '@/styles/main.scss';
import { Header } from '../components/header/Header';
import { Notification } from '@/components/notification/Notification';
import { ReduxProvider } from '@/components/ReduxProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={'container'}>
          <ReduxProvider>
            <Header />
            <Notification />
            {children}
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
